---
- name: Copy the SKELETON_APPLICATION systemd service file
  template:
    src: application.service.j2
    dest: /etc/systemd/system/SKELETON_APPLICATION.service
    owner: root
    group: root
    mode: 0644
  notify: restart SKELETON_APPLICATION
