---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - SKELETON_APPLICATION_install
    - SKELETON_APPLICATION_configure
    - SKELETON_APPLICATION_run

- import_tasks: preflight.yml
  tags:
    - SKELETON_APPLICATION_install
    - SKELETON_APPLICATION_configure
    - SKELETON_APPLICATION_run

- import_tasks: install.yml
  become: true
  tags:
    - SKELETON_APPLICATION_install

- import_tasks: configure.yml
  become: true
  tags:
    - SKELETON_APPLICATION_configure

- name: Ensure SKELETON_APPLICATION is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: SKELETON_APPLICATION
    enabled: true
  tags:
    - SKELETON_APPLICATION_run
